### PR TITLE
Master

### PR DESCRIPTION
**Pull request by Tbizla**
fix typo

### CODE REVIEW

**Comment by Ivshti** [comment]
What's changed here? github says nothing changed

**Comment by Tbizla** [comment]
Line 184 should have been changed. I guess something went wrong. I'll check tonight.

**Comment by m0k1** [comment]
@lvshti close this one ? :)

**Comment by Tbizla** [comment]
Yes its a fuckup from me

**Comment by Ivshti** [comment]
good, closed it

**Comment by Tbizla** [comment]
Thnx, ill try to review the dutch translation when my system is up and
running again.

**Pull request closed without merging**
