### PR TITLE
Updated Serbian language translation

### PR DESCRIPTION
**Pull request by nexiRS**
Major update of the translation.

- Switched from Latin to Cyrillic because it's an official letter in Serbia, according to the constitution;
- Fixed errors, grammatical mistakes, incorrect translations; 
- Finished the translation completely.

*If I notice any mistake, I'll correct it at a reasonable time.

NOTE: There is a problem that I don't know which string "Cast" refers to "Cast to... e.g. TV" (for easier understanding - which string refers to [this button](https://ibb.co/Vmzt3Nj)). Now, both strings are translated as "Глумци", but one of them should be "Пребацуј". I've noticed that this is a mistake in (almost) every translation. It'll be good if someone can explain this to me, in order to correct that.

### CODE REVIEW

**Comment by tymmesyde** [comment]
@nexiRS `CAST`, `SHOW_MORE_CAST` and `LINKS_CAST` are all related to actors / crew, the rest is related to casting on a device

**Review by jaruba — APPROVED** [review]

**Comment by jaruba** [comment]
@nexiRS thanks! will merge this one, if u have changes to do based on @tymmesyde 's answer, please create a new PR

**Comment by nexiRS** [comment]
> @nexiRS `CAST`, `SHOW_MORE_CAST` and `LINKS_CAST` are all related to actors / crew, the rest is related to casting on a device

But it seems like that probably the string `CAST` is used for both actors/crew and casting on a device. So, this means that cast (on a device) button is mistranslated as actors.

You can see an example of that in these [screenshots](https://imgur.com/a/WwPPSQq).

"Uloge" means "Actors" and "Актеры" means "Actors" too.

**Comment by tymmesyde** [comment]
@nexiRS Then it's an issue in the app, we will change the string used on the player to fix that

**Pull request merged**
