### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by m0k1**
Fixes and new translations

### CODE REVIEW

**Comment by m0k1** [comment]
I will tonight finish the rest of serbian language and fixes for it.
Please don't close this PR jet.

**Comment by Ivshti** [comment]
Thank you!

**Comment by Ivshti** [comment]
hehehe too late :)

**Comment by Ivshti** [comment]
If you just push more to your branch, the PR will automatically update, so don't worry

**Comment by m0k1** [comment]
Yea yea i know :) Expect more push's tonight.

**Pull request merged**
