### PR TITLE
Update vi-VN.json

### PR DESCRIPTION
**Pull request by ngocanhtve**
Complete the translation!

### CODE REVIEW

**Review by jaruba — APPROVED** [review]

**Comment by jaruba** [comment]
@ngocanhtve thanks!

**Comment by ngocanhtve** [comment]
Excuse me, but I have a question: the translation has been merged, why can't the app display the translation in the language?

**Comment by jaruba** [comment]
@ngocanhtve hi, translations are update when the apps are updated, we haven't had an update of the apps yet since this PR was merged, this should happen soon though (hopefully within a week)

**Comment by ngocanhtve** [comment]
@jaruba Since the first time I created a translation for the Vietnamese language. It has been merged into the original at PR #644 and the application has been updated many times. But in the display language selection list, there is still no option for Vietnamese. What I mean is that Vietnamese has not yet been added to the list of supported languages, and does not appear in the selection list, while since then there have been many updates to both the translation and the application.

**Comment by ngocanhtve** [comment]
@jaruba Stremio has just updated, but Vietnamese still does not appear in the display language selection list. I wonder if there's something missing that tells the app that there's a new language translation?

**Comment by ngocanhtve** [comment]
@jaruba Thank you so much for finding the crux of the problem. I'm willing to wait until the next update.

**Pull request merged**
