### PR TITLE
Rename Catalan filename for correct locale naming

### PR DESCRIPTION
**Pull request by pereorga**
"ca-ES" stands for Catalan as spoken in Spain. "CA" in "ca-CA" is the ISO country code for Canada.

### CODE REVIEW

**Comment by piotr-marendowski** [comment]
Is this the same situation as in #604?

**Comment by xeanhort** [comment]
Yes it is. I'm not sure about the issues mentioned there (loosing the configuration in the devices) or if the best option is to duplicate them.

In fact, I think the best option is to remove the country codes whenever possible and keep only the first part.

**Comment by pereorga** [comment]
@piotr-marendowski @xeanhort let me know if you want me to rebase this, or if you want me to switch to use `ca.json`.

**Comment by xeanhort** [comment]
[PR](https://github.com/Stremio/stremio-translations/pull/695) with the latest changes here. Once merged, @pereorga, you can proceed with the best approach to fix this

**Comment by pereorga** [comment]
@xeanhort thanks. I don't think it makes sense to keep rebasing this PR. Instead, I've created https://github.com/Stremio/stremio-translations/issues/696 to track the issue.

**Pull request closed without merging**
