### PR TITLE
Update pt-PT

### PR DESCRIPTION
**Pull request by SalvadorD18**
Translation of the new strings into pt-PT.

### CODE REVIEW

**Comment by jaruba** [comment]
@SalvadorD18 we managed to create conflicts with your branch when adding more strings, would it be possible for you to resolve them?

**Comment by SalvadorD18** [comment]
> @SalvadorD18 we managed to create conflicts with your branch when adding more strings, would it be possible for you to resolve them?

Yes, sure!

**Comment by SalvadorD18** [comment]
@jaruba can you tell me the context of these strings?:
-"STREMIO_TV_LIBRARY_MY": "My",
-"STREMIO_TV_SETTINGS_TUNNELLED_PLAYBACK": "Tunnelled Playback",
-"STREMIO_TV_SETTINGS_PROFILE_SOFT": "Soft",
-"SEEK_TIME_DURATION": "Seek Time Duration",

Thank you in advance!

**Comment by TheBeastLT** [comment]
@SalvadorD18 

- "STREMIO_TV_LIBRARY_MY" - This is a prefix for library catalogs. Ie. `My Movies`, `My Series`
- "STREMIO_TV_SETTINGS_TUNNELLED_PLAYBACK" - This is a player [setting](https://medium.com/google-exoplayer/tunneled-video-playback-in-exoplayer-84f084a8094d) name
- "STREMIO_TV_SETTINGS_PROFILE_SOFT" - This is an enum label for `Soft` torrent profile
- "SEEK_TIME_DURATION" - This is a label for the duration setting which is used when seeking video (with arrow keys)

**Pull request closed without merging**
