### PR TITLE
PT-BR

### PR DESCRIPTION
**Pull request by loopbackbr**
Atualização -- Correções + Dias da Semana + Gêneros
Att -- Corrections + Days of Week + Genres

### CODE REVIEW

**Comment by Ivshti** [comment]
Thanks.
Will include with the next build in a few days + improved casting support

**Comment by Ivshti** [comment]
Also, what does the word for Board mean? We should keep in mind that the board will at some point include recommendations too

**Comment by loopbackbr** [comment]
Thx, Ivo.

I think the word “Painel” is better then “Tabuleiro”.
“Painel” can be used for a grid with a sort of things that you can choose.
“Tabuleiro” sounds more like a “board game”, monopoly for example.

**Comment by Ivshti** [comment]
That makes sense. "Painel" is good then.

**Comment by loopbackbr** [comment]
Ivo,

In XBMC, we can get movie information on IMDb in language that we choose.
You think it’s a good idea make this in Stremio?



XBMC add ons XML

**Comment by Ivshti** [comment]
I have to think about it. I don't know any API/data source that provides IMDb data in a selected language, can you refer me to the XBMC plug-in?

**Comment by loopbackbr** [comment]
You can get this through HTTP request.
And there others DBs, like TVDb.

https://github.com/xbmc/repo-scrapers/tree/eden/metadata.common.imdb.com <https://github.com/xbmc/repo-scrapers/tree/eden/metadata.common.imdb.com>
https://github.com/xbmc/repo-scrapers/tree/eden/metadata.themoviedb.org <https://github.com/xbmc/repo-scrapers/tree/eden/metadata.themoviedb.org>
https://github.com/xbmc/repo-scrapers/tree/eden/metadata.tvdb.com <https://github.com/xbmc/repo-scrapers/tree/eden/metadata.tvdb.com>

https://github.com/xbmc/repo-scrapers/tree/eden <https://github.com/xbmc/repo-scrapers/tree/eden>

**Comment by loopbackbr** [comment]
Ivo,

I’ve made some research on XBMC and KODI code, and found how it’s made.

First the plugin search the movie title and get the movie ID, after that, it gather all the information about the movie.

The sequence is:

Search --
http://api.tmdb.org/3/search/movie?api_key=57983e31fb435df4df77afb854740ea9&query=Cut%20Bank&year=2014&language=pt

Movie Information --
http://api.tmdb.org/3/movie/276902?api_key=57983e31fb435df4df77afb854740ea9&language=pt
http://api.tmdb.org/3/movie/276902?api_key=57983e31fb435df4df77afb854740ea9&language=en

Cast Information --
http://api.tmdb.org/3/movie/276902/casts?api_key=57983e31fb435df4df77afb854740ea9

Releases Information --
http://api.tmdb.org/3/movie/276902/releases?api_key=57983e31fb435df4df77afb854740ea9&language=us

Strings Configuration --
http://api.tmdb.org/3/configuration?api_key=57983e31fb435df4df77afb854740ea9

Movie Posters --
http://api.tmdb.org/3/movie/276902/images?api_key=57983e31fb435df4df77afb854740ea9&language=pt
http://api.tmdb.org/3/movie/276902/images?api_key=57983e31fb435df4df77afb854740ea9&language=en
http://api.tmdb.org/3/movie/276902/images?api_key=57983e31fb435df4df77afb854740ea9

Movie Trailers --
http://api.tmdb.org/3/movie/276902/trailers?api_key=57983e31fb435df4df77afb854740ea9&language=pt
http://api.tmdb.org/3/movie/276902/trailers?api_key=57983e31fb435df4df77afb854740ea9&language=en



Unfortunately, IMDb API only show english info.

http://akas.imdb.com/find?q=Cut%20Bank&s=tt

http://akas.imdb.com/title/tt1661820/

http://akas.imdb.com/title/tt1661820/combined

**Comment by Ivshti** [comment]
That's pretty interesting, thank you!

We also use tvdb but we cache the results in our own DB, to mix with results from other APIs and to serve them quicker and to be able to do any kind of queries (e.g. get only the oscar winners). 

So the issue with this would be that this whole DB-based system would have to find space for strings in every language, which IMO would kill the performance.

A possible solution would be to have the app retrieve this information on demand, which is a better solution.

So there are two options: 
1) implement in in the app itself - this goes against the idea for the app to be only a lean GUI on top of our add-ons protocol, and not access any APIs
2) when making an meta.get call (the stremio add-ons protocol call to get full meta), pass a language field, and then have our Cinemeta add-on get the specific language strings from tvdb - this one seems doable, the problem is we won't have translations in Discover

I'll keep thinking about this

**Pull request merged**
