### PR TITLE
Μετάφραση εφαρμογής Android TV

### PR DESCRIPTION
**Pull request by Happy3450**

### CODE REVIEW

**Comment by jaruba** [comment]
@Happy3450 why did u close it? the translations seem ok

**Comment by Happy3450** [comment]
> @Happy3450 why did u close it? the translations seem ok

Sorry, I didn't notice. Do you know when this translation will be applied to the Android TV app?

**Comment by jaruba** [comment]
hopefully next week

**Comment by Happy3450** [comment]
> hopefully next week

Thank you so much! Have a good day! 😁

**Comment by Happy3450** [comment]
Hello! Will the translation be applied this week?

Στις Παρ 19 Αυγ 2022 στις 4:58 μ.μ., ο/η Alexandru Branza <
***@***.***> έγραψε:

**Pull request merged**
