### PR TITLE
Update and rename zh-HK.json to zh-TW.json

### PR DESCRIPTION
**Pull request by nayfaan**
* Renamed zh-HK to zh-TW (more commonly used naming for traditional Chinese)
* updated translations according to translations in zh-CN (zh-CN and zh-TW should be updated together as they are different writing of the same language as of current edition)

### CODE REVIEW

**Comment by jaruba** [comment]
@nayfaan 

1. When changing the language file name, you need to also change it in the list from `index.js`
2. I'm confused about which one would be correct between `zh-HK` and `zh-TW`, but this may not be merged because it will break the settings of all users that have currently selected `zh-HK`

**Comment by shanyan-wcx** [comment]
简体中文的翻译是我在做，我对繁体中文了解得不够多，虽然能够流畅阅读，但是无法直接书写，所以我没有把繁体的翻译也做了。据我所知，繁体的翻译中有很多词语与简体的说法并不相同，比如“program”这个词在繁体里似乎应该翻译为“程式”而非“程序”，而且台湾和香港的同一个繁体字的写法也有所不同。所以我认为繁体翻译不该直接由简体转化得来，而是应该重新翻译，并且同时保留zh-HK和zh-TW。

I'm doing the translation of simplified Chinese. I don't know enough about traditional Chinese. Although I can read smoothly, I can't write directly, so I didn't do the translation of traditional Chinese. As far as I know, many words in traditional Chinese translation are different from those in simplified Chinese. For example, the word "program" in traditional Chinese seems to be translated into "程式" rather than "程序", and the writing of the same traditional character in Taiwan and Hong Kong is also different. Therefore, I think traditional Chinese translation should not be directly converted from simplified Chinese, but should be re translated and retain zh-HK and zh-TW at the same time.

**Comment by nayfaan** [comment]
(繁體用者)

我覺得可以先套用簡中的用字，然後再待有人來修正。我覺得**有中文翻譯總比甚麽都沒翻為好**。簡中的用字其實對繁中的用戶來說都看得懂，只不過是會覺得有點太書面語化。

**Comment by nayfaan** [comment]
i think it's better to use the simplified character translation for now (in traditional form) until someone else can fix the nuances. I think having a Chinese translation for traditional is better than having no translation at all. simplified phrasing is not not understandable for traditional, just slightly bookish

**Comment by nayfaan** [comment]
as for both zh-HK and zh-TW, I agree. That is if this project have enough volunteers to do that

**Comment by shanyan-wcx** [comment]
那如果你不介意的话，我可以在更新简中的同时更新繁中，但有一个问题，就是如果之前有人修正了繁体翻译，与简体结构有所不同的话，这些修正会被我覆盖掉。其实如果你有空的话也可以自己翻译的，我也只是个用户而已。

**Comment by shanyan-wcx** [comment]
我利用opencc将简体转化成了本土化的台湾繁体，你看看有没有问题。

**Comment by jaruba** [comment]
@nayfaan 

Is this PR still needed after merging this one? https://github.com/Stremio/stremio-translations/pull/488

If so, please fix the conflicts so i can merge it

**Comment by jaruba** [comment]
closing this PR due to lack of activity

**Pull request closed without merging**
