### PR TITLE
Translated latest additions, plus some old ones that were never imple…

### PR DESCRIPTION
**Pull request by zurdyo**
…mented. Cheers!

### CODE REVIEW

**Comment by Ivshti** [comment]
Thanks, merged!

**Comment by zurdyo** [comment]
Great!

**Comment by zurdyo** [comment]
Hey Ivo,
There’s something that’s not clear to me. What’s the difference between these two commands?

"CTX_SHARE": "Share",
"CTX_COPY_SHARE_LINK": "Copy share link",

Is the second command simply a "copy link" one? In this case I’d have to change the translation.

Thanks,

Ian

**Comment by Ivshti** [comment]
@zurdyo They are different. The first one just specifies sharing in general, along with the social media options. The second one specifies copying a share link specifically

**Pull request merged**
