### PR TITLE
Hebrew translation for Stremio

### PR DESCRIPTION
**Pull request by kornbed**

### CODE REVIEW

**Comment by Ivshti** [comment]
Thank you! I've just been thinking that we need a Hebrew translation :)

**Comment by kornbed** [comment]
Happy to help, the only problem with Hebrew is RTL support, I can help with
the CSS if you want...

On Wed, Nov 25, 2015 at 11:29 AM, Ivo Georgiev <notifications@github.com>
wrote:

> Merged #4 <https://github.com/Stremio/stremio-translations/pull/4>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Stremio/stremio-translations/pull/4#event-474283988>.
>



-- 
בברכה,
מתן עמוס
ביבר גלובל בע"מ
סלולרי: 050-2223405
פקס: 03-524-2514
matan@beaverglobal.com
www.beaverglobal.com

**Comment by Ivshti** [comment]
First, I'll need to know what has to be done conceptually. Sorry for the ignorance, but does the entire UI has to be flipped for an RTL interface? I feel like I've seen it implemented like that in GNOME or somewhere

**Comment by kornbed** [comment]
Yes, the entire UI is flipping, and you see it everywhere, GNOME, KDE,
Windows and IOS also and every website which is in Hebrew/Arabic is also
flipped, most common thing to do is add a setting to the lang file with
something like IS_RTL=True, by that you can add a CSS file for RTL like
rtl.css, when needed it will be AFTER the main css and will change only
what needed to be changed...

I an a web developer, and I do it daily.
Example:
http://www.beaverglobal.com/clients/zp/   - English version of the site
http://www.beaverglobal.com/clients/zp/he/   - Hebrew version of the site

The main CSS remains, but in the Hebrew version the rtl.css is added after
the main CSS so it can overwrite it.


On Wed, Nov 25, 2015 at 12:31 PM, Ivo Georgiev <notifications@github.com>
wrote:

> First, I'll need to know what has to be done conceptually. Sorry for the
> ignorance, but does the entire UI has to be flipped for an RTL interface? I
> feel like I've seen it implemented like that in GNOME or somewhere
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Stremio/stremio-translations/pull/4#issuecomment-159565055>
> .
>



-- 
בברכה,
מתן עמוס
ביבר גלובל בע"מ
סלולרי: 050-2223405
פקס: 03-524-2514
matan@beaverglobal.com
www.beaverglobal.com

**Comment by Ivshti** [comment]
@kornbed what about http://help.dottoro.com/lcdvioxc.php ?

**Comment by kornbed** [comment]
Sound good!

BTW: the CSS property you are looking for is
direction: rtl;

more info:
http://www.w3.org/wiki/CSS/Properties/direction

**Comment by kornbed** [comment]
This is for the content and render only, not for setting the UI to flip.
in all RTL Languages everything need to be flipped in the UI, this is why
you put the direction: rtl; in the body of the page, when this is done,
everything will behave like it should.

so if this is a HTML page you put in the css:

html {
    direction: rtl;
}

On Thu, Nov 26, 2015 at 1:01 PM, Ivo Georgiev <notifications@github.com>
wrote:

> @kornbed <https://github.com/kornbed> what about
> http://help.dottoro.com/lcdvioxc.php ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Stremio/stremio-translations/pull/4#issuecomment-159881448>
> .
>



-- 
בברכה,
מתן עמוס
ביבר גלובל בע"מ
סלולרי: 050-2223405
פקס: 03-524-2514
matan@beaverglobal.com
www.beaverglobal.com

**Comment by Ivshti** [comment]
I added a rtl.css to this repo, and tried direction: rtl and it does convert a lot of things to rtl.

However, I need to fix a few things that are breaking when that is added and adjust a few absolute positions.

However, opening stremio in debugger with ". --development" at the end of the cmdline gives enough ability to adjust css and add the generated properties to rtl.css 

With the next release, Stremio is going to include the rtl.css file for rtl languages :)

**Pull request merged**
