### PR TITLE
Added 53 categories from Channels/Tv channels

### PR DESCRIPTION
**Pull request by skanin**
Added 53 categories from Channels/Tv channels + translation

### CODE REVIEW

**Comment by Ivshti** [comment]
Wow, this is impressive!

**Comment by Ivshti** [comment]
@skanin have you tested this translation in the app? Can we shorten the "IMDb Rating" string a bit somehow? Maybe just to "IMDb", because it overflows and wraps to two lines :(

**Comment by skanin** [comment]
@Ivshti Yes, i've tested it. It looks ok, but if it overflows, there is no problem of changin it to "IMDb" :) (See gyazo screenshots attatched).

[Screenshot 1](https://gyazo.com/575b681130bdad31f534901f5a19339a)
[Screenshot 2](https://gyazo.com/5ef3daaf37a05eb1572da0bc1f7466e1)

**Comment by Ivshti** [comment]
@skanin that was stupid of me, I was looking at the Dutch translation, sorry

**Comment by skanin** [comment]
@Ivshti No problem! :) Let me know if you find any flaws in the norwegian json though, or any missing strings!

**Pull request merged**
