### PR TITLE
update hr-hr.json

### PR DESCRIPTION
**Pull request by boljsa**
update hr-HR

### CODE REVIEW

**Comment by Ivshti** [comment]
what's the difference between hr-hr and hr-HR? they are two different files atm

**Comment by boljsa** [comment]
hr-HR.json is the right file

**Comment by m0k1** [comment]
@Ivshti 

remove https://github.com/Stremio/stremio-translations/blob/master/hr-hr.json from branch.

**Comment by Ivshti** [comment]
I will merge it now, compare the files, and delete the wrong one

**Pull request merged**
