### PR TITLE
Update it-IT.json

### PR DESCRIPTION
**Pull request by zurdyo**
Made some corrections and added the missing translations.

### CODE REVIEW

**Comment by Ivshti** [comment]
thank you!

**Comment by zurdyo** [comment]
Hey Ivo,
My pleasure!
I’m a professional translator, among other things. 
Lemme know if I can help in any way.
Cheers,
Ian

**Comment by Ivshti** [comment]
Great! I like that you shortened the IMDB Rating translation, so that it doesn't overflow :). You tested in the app, right?

**Comment by zurdyo** [comment]
I use it on a regular basis and I love it! ;)
I haven’t tested the Italian translation in it, though. 
There are other parts that can probably be shortened. 
Let me know if you want me to attempt that as well.

**Comment by Ivshti** [comment]
be careful with "add to library" / "remove from library" - that's the one that overflows most often

**Comment by zurdyo** [comment]
Ok, updated file with shorter versions. Lemme know if they fit.

**Comment by zurdyo** [comment]
Hey Ivo,
I was wondering whether there is a timeline for the introduction of HD torrents where I notice most of them, atm, are in low quality.
Thanks and keep up the great work!
Ian

**Comment by Ivshti** [comment]
@zurdyo  - we do not develop the torrent add-on, as you can see in the UI, so I cannot give you a timeline on that; the developer is relatively active, so it's probably going to happen

**Comment by zurdyo** [comment]
Great, thanks!
I will also be updating a few Italian translations that need improvement.
Z

**Pull request merged**
