### PR TITLE
Support for Hindi (India) 

### PR DESCRIPTION
**Pull request by kartikey54**

### CODE REVIEW

**Comment by kartikey54** [comment]
@jaruba

**Comment by jaruba** [comment]
@kartikey54 thank you for your hard work, but i cannot merge this because there are many JSON parsing error with your translation file

here are a few as an example:
Screenshot 2021-12-29 at 13 38 34

Screenshot 2021-12-29 at 13 38 19

**Comment by kartikey54** [comment]
@jaruba thank you for catching this! I've pushed the fixes

**Comment by jaruba** [comment]
@kartikey54 merged, thanks again!

**Pull request merged**
